version: '3'

services:
  ymple:
    image: ymple:1.0.0
    build:
      context: .
    container_name: ymple
    ports:
      - "1338:1338"
    networks:
      - overlay

  mongodb:
    image: mvertes/alpine-mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db
    networks:
      - overlay

volumes:
  db-data:

networks:
  overlay:
