version: 3

services:
  ymple:
    image: ymple:1.0.0
    depends_on:
      - mongodb
    build:
      context: .
    ports:
      - 1338:1338
    volumes:
      - app

  mongodb:
    image: mongo:latest
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - MONGO_INITDB_DATABASE="ymple"
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
